[versions]
androidGradlePlugin = "9.1.0"
androidGradlePluginLegacy = "8.13.2"
kotlin = "2.3.10"
junitJupiter = "6.0.3"
junitPlatform = "6.0.3"
mavenPublish = "0.36.0"
kotlinxSerializationJson = "1.10.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
